### ISSUE TITLE
standalone style nesting

### ISSUE THREAD

**Issue by antonkulaga** [japgolly/scalacss#57] opened 2015-08-24 00:16 UTC
It is clear how to nest styles one inside another in InlineMode, but it is not clear how it works in standalone mode (if it is implemented). It will be great if it will be possible to deal with style nesting in a similar to [LESS way](http://lesscss.org/features/#features-overview-feature-nested-rules)

**Comment by aminecmi** [comment] 2015-10-28 10:17
Any way to do this ?

**Comment by japgolly** [comment] 2016-01-19 22:37
I haven't looked at this because I've been using InlineMode exclusively for ages. I thought nesting worked fine in StandaloneMode. If there's a problem with it, a test case to demonstrate what the problem is would be helpful. A problem of this kind sounds like a small fix. PR would be appreciated.

**Comment by japgolly** [comment] 2016-02-16 00:42
I believe this works (with a substantial bugfix to nesting about to be released in 0.4.0). If it's still a problem with 0.4.0 please reopen and add a snippet to demonstrate the problem. Thanks.

**Closed by japgolly** 2016-02-16 00:42 UTC
